"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { Crown, ArrowLeft } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen">
      <nav className="sticky top-0 z-50 border-b border-border/50 bg-background/80 backdrop-blur-xl">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
          <div className="flex h-14 items-center justify-between">
            <Link href="/" className="flex items-center gap-2.5">
              <div className="flex h-7 w-7 items-center justify-center rounded-md bg-primary/10">
                <Crown className="h-4 w-4 text-primary" />
              </div>
              <span className="text-sm font-bold tracking-tight">
                Chess Coach
              </span>
            </Link>
            <Link
              href="/"
              className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors"
            >
              <ArrowLeft className="h-3.5 w-3.5" />
              Home
            </Link>
          </div>
        </div>
      </nav>

      <motion.div
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.3 }}
        className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 py-12"
      >
        <h1 className="text-3xl font-bold tracking-tight mb-2">
          Terms of Service
        </h1>
        <p className="text-sm text-muted-foreground mb-8">
          Last updated: February 11, 2026
        </p>

        <div className="prose prose-sm prose-invert max-w-none space-y-6 text-muted-foreground">
          <section>
            <h2 className="text-lg font-semibold text-foreground">
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing or using AI Chess Coach, you agree to be bound by
              these Terms of Service. If you do not agree, please do not use the
              service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">
              2. Description of Service
            </h2>
            <p>
              AI Chess Coach is a web application that provides AI-powered chess
              analysis, game import from Lichess, puzzle training, opening
              exploration, and personalized coaching feedback. The service uses
              third-party APIs including Lichess and Claude AI.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">
              3. Not Professional Coaching
            </h2>
            <p>
              The AI-generated analysis and coaching feedback are for
              educational and entertainment purposes only. They should not be
              considered a substitute for professional chess instruction. AI
              analysis may contain errors or inaccuracies.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">
              4. AI-Generated Content
            </h2>
            <p>
              Coaching feedback and game analysis are generated by AI (Claude by
              Anthropic). While we strive for accuracy, AI-generated content may
              occasionally be incorrect. We recommend verifying important
              analysis with established chess engines.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">
              5. User Data
            </h2>
            <p>
              Game data, puzzle statistics, and settings are stored locally in
              your browser using localStorage. We do not store your personal
              game data on our servers. Lichess data is fetched directly from the
              Lichess public API on your behalf.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">
              6. Acceptable Use
            </h2>
            <p>
              You agree not to misuse the service, including but not limited to:
              attempting to overload the service with excessive requests,
              scraping or automated access beyond normal use, or using the
              service to facilitate cheating in online chess.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">
              7. Beta Service
            </h2>
            <p>
              AI Chess Coach is currently in beta. Features may change, be
              added, or removed without notice. The service is provided free of
              charge during the beta period. We make no guarantees about uptime
              or availability.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">
              8. Limitation of Liability
            </h2>
            <p>
              AI Chess Coach is provided &ldquo;as is&rdquo; without warranty of
              any kind. We are not liable for any damages arising from your use
              of the service, including but not limited to loss of data or
              inaccurate analysis.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">
              9. Changes to Terms
            </h2>
            <p>
              We reserve the right to modify these terms at any time. Continued
              use of the service after changes constitutes acceptance of the
              updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">
              10. Contact
            </h2>
            <p>
              For questions about these terms, please reach out via the waitlist
              email or through our GitHub repository.
            </p>
          </section>
        </div>
      </motion.div>

      <footer className="border-t border-border/50 py-6">
        <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 flex justify-between text-xs text-muted-foreground">
          <span>AI Chess Coach</span>
          <Link href="/privacy" className="hover:text-foreground transition-colors">
            Privacy Policy
          </Link>
        </div>
      </footer>
    </div>
  );
}
